import { list } from "postcss";

const translations = {
  ru: {
    home: 'Главная',
    doctors: 'Доктора',
    contacts: 'Чаты',
    about: 'О нас',
    profile: 'Мой профиль',
    appointments: 'Мои записи',
    logout: 'Выйти',
    createAccount: 'Создать аккаунт',

    // главная
    title: "Записаться на прием ",
    title2: "к проверенным врачам",
    subtitle: "Просмотрите наш список проверенных врачей ",
    subtitle2: "запланируйте встречу без проблем",
    zapisatsya: "Записаться",
    speciality: "Специальности",
    specialityAdd: "Просмотрите и запишитесь к нашим квалифицированным врачам",
    thebestdoc: "Лучшие врачи",
    thebestdocAdd: "Просмотрите наш обширный список доверенных врачей.",
    thebestdocMore: "Еще лучшие врачи",
    topDoctorsDescription: "Просмотрите наш обширный список доверенных врачей.",
    topDoctorsTitle: "Лучшие врачи",
    more: "Еще",
    banner1: "Запишись на прием",
    banner2: "У нас 100+ проверенных процедур",
    zapis: "Создать запись",
    company: 'КОМПАНИЯ',
    contactUs: 'СВЯЖИТЕСЬ С НАМИ',
    description: 'BioCare - забота о жизни. Мы были основаны в 2007 году и с тех пор мы улучшаем наше лечение и подход к клиентам. Мы будем рады, если вы посетите нашу клинику или порекомендуете нас своим друзьям!',
    copyright: '© 2025 «BioCare». Все права защищены. Использование материалов допускается с указанием активной ссылки на сайт BioCare.kz',
    available: 'Доступно',
    notAvailable: 'Недоступно',
    specialitydoc: {
      'Главный врач': 'Главный врач',
      'Гинеколог': 'Гинеколог',
      'Дерматолог': 'Дерматолог',
      'Педиатр': 'Педиатр',
      'Невролог': 'Невролог',
      'Гастроэнтеролог': 'Гастроэнтеролог'
    },
    // чаты
    spisok: "Список докторов",
    sendMessage: "Введите сообщение...",
    chooseDoctor: "Выберите врача",
    introTitle: "AI Доктор",
    preventionTitle: "Профилактика",
    preventionText: "Помогаем следить за здоровьем и предотвращать болезни заранее.",
    friendTitle: "Ваш друг",
    friendText: "Ваш надежный медицинский помощник всегда рядом.",
    remindersTitle: "Напоминания",
    remindersText: "Напоминаем вовремя о приеме лекарств и визите к врачу.",
    sendError: "Что-то пошло не так. Попробуйте позже.",
    aboutTitle: "О",
    aboutUs: "НАС",
    aboutText1: "Добро пожаловать в BioCare — вашего надежного партнёра в управлении медицинскими услугами удобно и эффективно. Мы понимаем, как сложно бывает записаться к врачу и управлять своими медицинскими данными.",
    aboutText2: "Prescripto стремится к совершенству в области медицинских технологий. Мы постоянно улучшаем нашу платформу, интегрируя новейшие достижения, чтобы обеспечить лучший пользовательский опыт. Мы рядом на каждом этапе — от первой записи до постоянного наблюдения.",
    visionTitle: "Наша миссия",
    visionText: "Наша цель — создать бесшовный опыт в сфере здравоохранения для каждого пользователя. Мы хотим сократить дистанцию между пациентами и врачами, чтобы вы могли получать помощь тогда, когда она вам нужна.",
    whyTitle: "ПОЧЕМУ",
    whyUs: "МЫ",
    efficiencyTitle: "ЭФФЕКТИВНОСТЬ",
    efficiencyText: "Оптимизированная запись на прием, которая вписывается в ваш загруженный график.",
    professionalismTitle: "ПРОФЕССИОНАЛИЗМ",
    professionalismText: "Доступ к сети проверенных медицинских специалистов в вашем регионе.",
    personalizationTitle: "ПЕРСОНАЛИЗАЦИЯ",
    personalizationText: "Индивидуальные рекомендации и напоминания, чтобы вы не забывали заботиться о себе.",
    avatar: "Аватар",
    update_error: "Ошибка при обновлении данных",
    update_failed: "Не удалось обновить профиль",
    loading: "Загрузка данных профиля...",
    contact_info: "Контактная информация",
    phone: "Телефон",
    address: "Адрес",
    personal_info: "Личная информация",
    gender: "Пол",
    male: "Мужской",
    female: "Женский",
    dob: "Дата рождения",
    save: "Сохранить",
    edit: "Редактировать",
    blizhaishie: "Ближайшие записи",
    noblizhaishie: "Нет ближайших записей",
    timedate: "Дата & Время:",
    onlinePay: "Оплатить онлайн",
    onlineDone: "Оплачено",
    cansel: "Отменить",
    history: "История",
    nohistory: "У вас пока нет истории записей.",
    completed: "Завершен",
    canceled: "Отменен",
    loadpay: "Загрузка оплаты...",
    pay: "Оплатить",
    login: 'Войти',
    please: 'Пожалуйста',
    register: 'зарегистрируйтесь',
    signInToBook: 'войдите для записи',
    fullName: 'ФИ',
    password: 'Пароль',
    haveAccount: 'Уже есть аккаунт?',
    loginHere: 'Войти здесь',
    newAccount: 'Создать новый аккаунт?',
    clickHere: 'Нажмите сюда',
    successLogin: 'Вы вошли!',
    errorLogin: 'Ошибка при входе. Попробуйте снова.',
    alreadyExists: 'Аккаунт с такой почтой уже существует.',
    wrongCredentials: 'Неверная почта или пароль.',
    errorTryAgain: 'Ошибка при входе или регистрации. Попробуйте снова.',


    // admin
    allapp: "Все записи",
    patient: "Пациент",
    age: "Возраст",
    doctor: "Доктор",
    fee: "Стоимость",
    operation: "Операция",
    areyousure: "Вы уверены, что хотите отменить запись?",
    yes: "Да",
    no: "Отмена",
    add_doctor: "Добавить доктора",
    upload_image: "Загрузить картинку доктора",
    doctor_name: "Имя доктора",
    name: "Имя",
    doctor_email: "Почта доктора",
    doctor_password: "Пароль доктора",
    experience: "Опыт",
    year: "лет",
    fees: "Стоимость",
    specialist_gp: "Главный врач",
    specialist_gynecologist: "Гинеколог",
    specialist_dermatologist: "Дерматолог",
    specialist_pediatrician: "Педиатр",
    specialist_neurologist: "Невролог",
    specialist_gastroenterologist: "Гастроэнтеролог",
    degree: "Квалификация",
    address1: "Адрес 1",
    address2: "Адрес 2",
    about1: "Подробнее",
    about_placeholder: "Напишите подробнее про доктора",
    submit_add_doctor: "Добавить доктора",
    success_doctor_added: "Доктор успешно добавлен",
    error_fill_all_fields: "Пожалуйста, заполните все поля и загрузите изображение.",
    error_adding_doctor: "Ошибка при добавлении",
    error_generic: "Произошла ошибка",
    patients: "Пациенты",
    latestapp: "Последние записи",
    panel: "Панель управления",
    zapici: "Записи",
    send: "Отправить",
    list: "Список клиентов",
    clientswill: "Клиенты появятся здесь",
    choosedoc: "Выберите пользователя, чтобы начать чат",
    email: "Почта",
    months: [
      "Январь", "Февраль", "Март", "Апрель", "Май", "Июнь",
      "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"
  ],
  weekdaysShort: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
  zapisi_na: "Записи на",
  no_zapisi: "Нет записей на эту дату.",
  close: "Закрыть",
  Chat: "Чат",
  DocProfile: "Профиль врача",
  Appointments: "Записи",
  Dashboard: "Панель управления",
  AllAppointments: "Все записи",
  payment: "Оплата",
  Action: "Действие",
  AppComplete: "Приём завершён!",
  Duration: "Длительность:",
  AppStart: "Начало приёма:",
  min: "минут",
  ok: "Ок",
  Areyousure: "Вы уверены, что хотите отменить запись?",
  AppFee: "Стоимость приёма:",
  Tune: "Настройка",
  AddApp: "Добавить запись",
  SettingSlots: "Настройка слотов",
  Manual: "Ручное создание слотов",
  auto: "Автоматическая генерация слотов",
  emailCLient: "Почта клиента",
  Appotime: "Время приёма:",
  Appodate: "Дата приёма:",
  add: "Добавить",
  faceSaved: "Фото сохранено",
  optionalFaceRegistration: "Регистрация Face ID (по желанию)",
  cancel: "Отмена",
  confirm: "Подтвердить",





  },
  en: {
    home: 'Home',
    doctors: 'Doctors',
    contacts: 'Chats',
    about: 'About',
    profile: 'My Profile',
    appointments: 'My Appointments',
    logout: 'Logout',
    createAccount: 'Create account',
    title: "Book an appointment",
    title2: "With trusted doctors",
    subtitle: "Simply browse through our extensive list of trusted doctors",
    subtitle2: "schedule your appointment hassle-free",
    zapisatsya: "Book an appointment",
    speciality: "Find by speciality",
    specialityAdd: "Browse and book an appointment with our qualified doctors",
    thebestdoc: "Top doctors to book",
    thebestdocAdd: "Simply browse through our extensive list of trusted doctors",
    thebestdocMore: "More top doctors",
    topDoctorsDescription: "Find the most qualified doctors ready to help you.",
    topDoctorsTitle: "Top Doctors",
    more: "More",
    banner1: "Book an appointment",
    banner2: "With 100+ trusted doctors",
    zapis: "Create an appointment",
    company: 'COMPANY',
    contactUs: 'CONTACT US',
    description: 'BioCare - caring for life. We were founded in 2007 and since then have improved our treatment and client approach. We would be happy if you visit our clinic or recommend us to your friends!',
    copyright: '© 2025 “BioCare”. All rights reserved. Use of materials is permitted with an active link to BioCare.kz',
    available: 'Available',
    notAvailable: 'Not available',
    specialitydoc: {
      'Главный врач': 'Chief Doctor',
      'Гинеколог': 'Gynecologist',
      'Дерматолог': 'Dermatologist',
      'Педиатр': 'Pediatrician',
      'Невролог': 'Neurologist',
      'Гастроэнтеролог': 'Gastroenterologist'
    },
    // чаты
    spisok: "List of doctors",
    sendMessage: "Send message...",
    chooseDoctor: "Choose a doctor",
    introTitle: "AI Doctor",
    preventionTitle: "Prevention",
    preventionText: "Helping you monitor your health and prevent illnesses in advance.",
    friendTitle: "Your Friend",
    friendText: "Your trusted medical friend and helper is always there for you.",
    remindersTitle: "Reminders",
    remindersText: "Reminding you on time to take your medications and see your doctor.",
    sendError: "Something went wrong. Try again later.",


    aboutTitle: "ABOUT",
    aboutUs: "US",
    aboutText1: "Welcome to BioCare, your trusted partner in managing your healthcare needs conveniently and efficiently. At Prescripto, we understand the challenges individuals face when it comes to scheduling doctor appointments and managing their health records.",
    aboutText2: "Prescripto is committed to excellence in healthcare technology. We continuously strive to enhance our platform, integrating the latest advancements to improve user experience and deliver superior service. Whether you're booking your first appointment or managing ongoing care, Prescripto is here to support you every step of the way.",
    visionTitle: "Our Vision",
    visionText: "Our vision at Prescripto is to create a seamless healthcare experience for every user. We aim to bridge the gap between patients and healthcare providers, making it easier for you to access the care you need, when you need it.",
    whyTitle: "WHY",
    whyUs: "US",
    efficiencyTitle: "EFFICIENCY",
    efficiencyText: "Streamlined appointment scheduling that fits into your busy lifestyle.",
    professionalismTitle: "PROFESSIONALISM",
    professionalismText: "Access to a network of trusted healthcare professionals in your area.",
    personalizationTitle: "PERSONALIZATION",
    personalizationText: "Tailored recommendations and reminders to help you stay on top of your health.",
    avatar: "Avatar",
    update_error: "Profile update error",
    update_failed: "Failed to update profile",
    loading: "Loading profile data...",
    contact_info: "Contact Information",
    phone: "Phone",
    address: "Address",
    personal_info: "Personal Information",
    gender: "Gender",
    male: "Male",
    female: "Female",
    dob: "Date of Birth",
    save: "Save",
    edit: "Edit",
    blizhaishie: "Upcoming appointments",
    noblizhaishie: "No upcoming appointments",
    timedate: "Date & Time:",
    onlinePay: "Pay online",
    onlineDone: "Paid",
    cansel: "Cancel",
    history: "History",
    nohistory: "You currently have no appointment history.",
    completed: "Completed",
    canceled: "Canceled",
    loadpay: "Loading ...",
    pay: "Pay",

    login: 'Login',
    please: 'Please',
    register: 'register',
    signInToBook: 'sign in to book',
    fullName: 'Full Name',
    password: 'Password',
    haveAccount: 'Already have an account?',
    loginHere: 'Login here',
    newAccount: 'Create a new account?',
    clickHere: 'Click here',
    successLogin: 'Successfully logged in!',
    errorLogin: 'Login error. Try again.',
    alreadyExists: 'An account with this email already exists.',
    wrongCredentials: 'Incorrect email or password.',
    errorTryAgain: 'Login or registration failed. Try again.',
    // english translations
    allapp: "All appointments",
    patient: "Patient",
    age: "Age",
    doctor: "Doctor",
    fee: "Fee",
    operation: "Operation",
    areyousure: "Are you sure you want to cancel the appointment?",
    yes: "Yes",
    no: "Cancel",
    // english translations
    add_doctor: "Add doctor",
    upload_image: "Upload doctor's image",
    doctor_name: "Doctor's name",
    name: "Name",
    doctor_email: "Doctor's email",
    doctor_password: "Doctor's password",
    experience: "Experience",
    year: "years",
    fees: "Fees",
    specialist_gp: "Chief doctor",
    specialist_gynecologist: "Gynecologist",
    specialist_dermatologist: "Dermatologist",
    specialist_pediatrician: "Pediatrician",
    specialist_neurologist: "Neurologist",
    specialist_gastroenterologist: "Gastroenterologist",
    degree: "Qualification",
    address1: "Address 1",
    address2: "Address 2", 
    about1: "More details",
    about_placeholder: "Write more about the doctor",
    submit_add_doctor: "Add doctor",
    success_doctor_added: "Doctor successfully added",
    error_fill_all_fields: "Please fill in all the fields and upload an image.",
    error_adding_doctor: "Error adding doctor",
    error_generic: "An error occurred",
    patients: "Patients",
    latestapp: "Latest appointments",
    panel: "Control Panel",
    zapici: "Appointments",
    send: "Send",
    list: "List of clients",
    clientswill: "Clients will appear here",
    choosedoc: "Choose a user to start a chat",
    email: "Email",
    months: [
      "January", "February", "March", "April", "May", "June",
      "July", "August", "September", "October", "November", "December"
  ],
  weekdaysShort: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  zapisi_na: "Appointments on",
  no_zapisi: "No appointments on this date.",
  close: "Close",
  Chat: "Chat",
  DocProfile: "Doctor Profile",
  Appointments: "Appointments",
  Dashboard: "Dashboard",
  AllAppointments: "All Appointments",
  payment: "Payment",
  Action: "Action",
  AppComplete:"Appointment completed!",
  Duration: "Duration:",
  AppStart: "Appointment Start:",
  min: "minutes",
  ok: "Ok",
  Areyousure: "Are you sure you want to cancel the appointment?",
  AppFee: "Appointment Fee:",
  Tune: "Tune",
  AddApp: "Add Appointment",
  SettingSlots: "Setting up slots",
  Manual: "Manual creation of slots",
  auto: "Automatic slot generation",
  emailCLient: "Client's email",
  Appotime: "Appointment time:",
  Appodate: "Appointment date:",
  add: "Add",
  faceSaved: "Photo saved",
  optionalFaceRegistration: "Face ID registration (optional)",
  cancel: "Cancel",
  confirm: "Confirm",




  }
}

export default translations;
